import './globals.css'
import { DM_Sans } from 'next/font/google'

import Nav from '@/components/Nav';
import BottomBar from '@/components/BottomBar';

const dm_sans = DM_Sans({ subsets: ['latin'], weight: '400', variable: '--dm-font' })

export const metadata = {
  title: 'Sustainability Marketplace',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} bg-egg-shell`}>
        <main>
          <header>
            <Nav />
          </header>
          {children}
          <footer>
            <BottomBar />
          </footer>
        </main>
      </body>
    </html>
  )
}
